name: 'svgg_mcmc'
make_setter: make_mcmc_svgg
plot: False

criterion:
  alpha: 2
  beta: 2
  temp: 2

sp_model:
  layers: [128, 128]
  optimize_every_x_steps: 5_000
  batch_size: 100
  history_length: 200
  k_steps_optimization: 100
  weight_decay: 1e-3

prior:
  gamma: 0.1
  ood_percent: 0.01
  batch_size: 1000
  optimize_every_x_steps: 5_000

mcmc:
  noise_sigma: 0.5
  nb_steps: 10_000