defaults:
  - method: default
  - _self_

save_episode: True

seed: 0

env:
  max_episode_steps: 50
  num_envs: 20
  env_id: 'AntMaze_HardestMaze-v3'
  xml_files: None
  num_eval_rollout: 250
  change_env_steps_list: None

actor:
  gamma: 0.98
  actor_lr: 1e-3
  actor_layers: [512,512,512]
  critic_lr: 1e-3
  critic_layers: [512,512,512]
  tau: 5e-2
  target_update_period: 10
  buffer_size: 3_000_000
  batch_size: 2000
  gd_steps_per_step: 0.5
  max_steps: 3_000_000
  evaluate_every_x_steps: 5_000
  save_agent_every_x_steps: 100_000
  

  